[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
[features]
log_error = []
log_warn  = []
log_info  = []
log_debug = []
log_trace = []
